
name: componly-04f9b11c-ccd5-4735-ac63-fc8b194db8db-97e7d0bc-3458-43c8-905a-ff893cf121b8

on:
  workflow_dispatch:
   inputs:
      commitName:
        description: 'Custom commit name'
        required: true
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspaces:
          - ./

    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18

      - name: Install dependencies
        id: install-dependencies
        run: |
        
                echo -e "\n@componly:registry=https://npm.pkg.github.com/" >> .npmrc
                echo //npm.pkg.github.com/:_authToken=${{ secrets.COMPONLY_NPM_AUTH_TOKEN }} >> .npmrc
                if [[ "${{ matrix.workspaces}}" != "empty" ]]; then
                    pwd
                    pushd ${{ matrix.workspaces }} 
                    yarn install --no-lockfile && yarn add @componly/core  @componly/cli  @componly/schemas  axios -D --no-lockfile
                    popd
                else
                    echo "No workspaces to install. Running 'yarn install' in the root directory."
                    yarn install --no-lockfile && yarn  add @componly/core  @componly/cli  @componly/schemas  axios -D --no-lockfile
                fi
      
      - name: Scan
        id: componly-scan
        env:
          COMMIT_NAME: ${{ github.event.head_commit.message || github.event.inputs.commitName }}
          RUN_ID: ${{ github.run_id }}
          COMMIT_HASH: ${{ github.sha }}
          STEP_OUTCOME: ${{ steps.componly-scan.outcome }}
          JOB_NAME: ${{ github.job }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
          COMPONLY_BACKEND_URL: https://a7fd-105-235-129-8.ngrok-free.app
          COMPONLY_CLI_ENV: development
        run: |
          ls -a 
          cd  ${{ matrix.workspaces }}   
          npx componly scan --cli-id=${{secrets.COMPONLY_API_KEY}} --cli-password="${{secrets.COMPONLY_API_SECRET}}" --config-path ./   --project  ./

